on: [push]
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    # From here we just define all the steps that we have to do.
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        
      # Install golang
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.5

      - name: Installing Subfinder, HTTPX, Nuclei, Nikto, 
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
          sudo apt-get update
          sudo apt-get install nmap
          
      - name: Running nmap
        run: |
            mkdir -p output/$(head -1 targets.txt)
            nmap -oN output/$(head -1 targets.txt)/$(head -1 targets.txt)-nmap-out.txt -iL targets.txt
            
      - name: Running Subfinder
        run: |
           subfinder -dL targets.txt -o output/$(head -1 targets.txt)/$(head -1 targets.txt)-subfinder-out.txt
            
      - name: Running HTTPX
        run: |
          cat output/$(head -1 targets.txt)/subfinder.txt output/$(head -1 targets.txt)/$(head -1 targets.txt)-subfinder-out.txt|httpx -silent -o output/$(head -1 targets.txt)/$(head -1 targets.txt)-httpx-out.txt

      - name: Save domains
        run: |
          git config --local user.email "jineebjn@gmail.com"
          git config --local user.name "jineebjn"
          git add --all
          git commit -m "Updated"          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: 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
