name: Recon Workflow

on: [push]
permissions: write-all

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install -v github.com/tomnomnom/httprobe@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Prepare Target
        id: prep
        run: |
          target=$(head -1 targets.txt)
          echo "target=$target" >> $GITHUB_ENV
          mkdir -p output/$target

      - name: Run Nmap
        run: |
          nmap -p- -sV "$target" -v -oN output/$target/nmap.txt

      - name: Run Subfinder and Deduplicate
        run: |
          subfinder -d "$target" -silent > output/$target/subs.txt
          sort -u output/$target/subs.txt > output/$target/subs_uniq.txt

      - name: Run Httprobe on Subdomains
        run: |
          cat output/$target/subs_uniq.txt | httprobe > output/$target/live.txt

      - name: Commit and Push Results
        run: |
          git config --local user.email "jineebjn@gmail.com"
          git config --local user.name "jineebjn"
          git add output/
          git commit -m "Automated recon result for $target" || echo "Nothing to commit"
        continue-on-error: true

      - name: Push to Repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_PAT }}
